import { readFile, writeFile } from "node:fs/promises"
import { resolve, join } from "node:path"
import { existsSync } from "node:fs"

export interface SkillScore {
  name: string
  uses: number
  successes: number
  failures: number
  avgCompletionPct: number
  lastUsed: string | null
}

const SCORE_FILE = resolve(process.cwd(), ".aegis/skills/scores.json")
const SKILLS_DIR = resolve(process.cwd(), "skills")
const CURATOR_DIR = resolve(process.cwd(), ".aegis/skills")

export class SkillCurator {
  private scores: SkillScore[] = []

  async initialize(): Promise<void> {
    const { mkdir } = await import("node:fs/promises")
    await mkdir(CURATOR_DIR, { recursive: true })

    if (existsSync(SCORE_FILE)) {
      try {
        const raw = await readFile(SCORE_FILE, "utf-8")
        this.scores = JSON.parse(raw)
      } catch {
        this.scores = []
      }
    } else {
      this.scores = []
    }
  }

  async recordUse(name: string, success: boolean, completionPct: number): Promise<void> {
    const existing = this.scores.find((s) => s.name === name)
    const now = new Date().toISOString()

    if (existing) {
      existing.uses++
      if (success) existing.successes++
      else existing.failures++
      existing.avgCompletionPct = Math.round(
        (existing.avgCompletionPct * (existing.uses - 1) + completionPct) / existing.uses,
      )
      existing.lastUsed = now
    } else {
      this.scores.push({
        name,
        uses: 1,
        successes: success ? 1 : 0,
        failures: success ? 0 : 1,
        avgCompletionPct: completionPct,
        lastUsed: now,
      })
    }

    await this.persist()
  }

  async getScore(name: string): Promise<SkillScore | undefined> {
    return this.scores.find((s) => s.name === name)
  }

  async listScores(): Promise<SkillScore[]> {
    return [...this.scores].sort((a, b) => b.uses - a.uses)
  }

  // ── Experience-based skill generation ─────────────────────────────

  async proposeSkillFromRun(
    conversationSummary: string,
    agentType: string,
  ): Promise<{ name: string; content: string } | null> {
    const workflowIndicators = [
      "repeatedly used",
      "every time",
      "always start by",
      "follow the same process",
      "standard workflow",
      "typical approach",
    ]

    const hasWorkflow = workflowIndicators.some((ind) => conversationSummary.toLowerCase().includes(ind))
    if (!hasWorkflow) return null

    const name = `${agentType}-workflow-${Date.now().toString(36)}`
    const content = [
      "---",
      `name: ${name}`,
      `description: Auto-generated workflow from ${agentType} agent experience`,
      `tags: [auto-generated, ${agentType}, workflow]`,
      "---",
      "",
      `# ${name}`,
      "",
      "## Workflow",
      "",
      conversationSummary,
      "",
      "## Notes",
      "",
      "- Auto-generated by SkillCurator",
      `- Source: ${agentType} agent`,
      `- Generated: ${new Date().toISOString()}`,
      "",
    ].join("\n")

    return { name, content }
  }

  async saveProposedSkill(name: string, content: string): Promise<string> {
    const { mkdir } = await import("node:fs/promises")
    const skillDir = join(SKILLS_DIR, name)
    await mkdir(skillDir, { recursive: true })
    const skillPath = join(skillDir, "SKILL.md")
    await writeFile(skillPath, content, "utf-8")
    return skillPath
  }

  // ── Pruning ────────────────────────────────────────────────────────

  async pruneLowScorers(threshold = 0.3): Promise<string[]> {
    const pruned: string[] = []
    const now = Date.now()

    for (const score of this.scores) {
      const successRate = score.uses > 0 ? score.successes / score.uses : 0
      const isOld = score.lastUsed ? now - new Date(score.lastUsed).getTime() > 30 * 24 * 60 * 60 * 1000 : true

      if (successRate < threshold && isOld) {
        const skillDir = join(SKILLS_DIR, score.name)
        if (existsSync(skillDir)) {
          const { rm } = await import("node:fs/promises")
          await rm(skillDir, { recursive: true, force: true })
          pruned.push(score.name)
        }
      }
    }

    if (pruned.length > 0) {
      this.scores = this.scores.filter((s) => !pruned.includes(s.name))
      await this.persist()
    }

    return pruned
  }

  async getStats(): Promise<{ totalSkills: number; totalUses: number; avgSuccessRate: number; avgCompletion: number }> {
    const total = this.scores.length
    const totalUses = this.scores.reduce((s, x) => s + x.uses, 0)
    const totalSuccesses = this.scores.reduce((s, x) => s + x.successes, 0)
    const totalCompletion = this.scores.reduce((s, x) => s + x.avgCompletionPct, 0)

    return {
      totalSkills: total,
      totalUses,
      avgSuccessRate: totalUses > 0 ? totalSuccesses / totalUses : 0,
      avgCompletion: total > 0 ? totalCompletion / total : 0,
    }
  }

  private async persist(): Promise<void> {
    const { mkdir } = await import("node:fs/promises")
    await mkdir(CURATOR_DIR, { recursive: true })
    await writeFile(SCORE_FILE, JSON.stringify(this.scores, null, 2), "utf-8")
  }
}

export const skillCurator = new SkillCurator()
