import { loadCiConfig, findRepoConfig } from "./config"
import { investigate } from "./investigator"
import { createPr, createDraftPr } from "./pr-creator"
import { autoMerge } from "./merger"
import { notify } from "./notifier"
import type { CiFixRequest, CiFixStatus } from "./types"

// Per-repo queue to prevent parallel runs
const repoQueues = new Map<string, Promise<void>>()

const activeRuns = new Map<string, CiFixStatus>()

export async function handleCiFixRequest(params: CiFixRequest): Promise<CiFixStatus> {
  const config = loadCiConfig()
  const repoConfig = findRepoConfig(config, params.repo)

  if (!repoConfig) {
    return {
      run_id: params.run_id,
      repo: params.repo,
      status: "failed",
      cost_usd: 0,
      started_at: Date.now(),
      completed_at: Date.now(),
      error: "Repo not configured in ~/.aegis/ci.yaml",
    }
  }

  const budget = params.budget_usd ?? repoConfig.budget_usd

  // Queue per-repo
  const runKey = params.repo
  const previous = repoQueues.get(runKey) ?? Promise.resolve()

  const runPromise = previous.then(async () => {
    const status: CiFixStatus = {
      run_id: params.run_id,
      repo: params.repo,
      status: "investigating",
      started_at: Date.now(),
      cost_usd: 0,
    }
    activeRuns.set(params.run_id, status)

    try {
      // 1. Investigate
      const investigation = await investigate({
        repo: params.repo,
        runId: params.run_id,
        headSha: params.head_sha,
        logsUrl: params.logs_url,
        budgetUsd: budget,
        model: repoConfig.model,
      })

      status.cost_usd = investigation.cost_usd

      if (!investigation.success || !investigation.fix_branch) {
        status.status = "failed"
        status.error = investigation.error ?? "Investigation failed"
        status.completed_at = Date.now()
        await notify({
          channels: repoConfig.notify,
          repo: params.repo,
          runId: params.run_id,
          status: "failed",
          error: status.error,
        })
        return
      }

      // 2. Create PR
      const prBody = [
        `## Auto-fix for failed CI run #${params.run_id}`,
        "",
        `**Repo:** ${params.repo}`,
        `**Run:** ${params.run_id}`,
        ...(params.head_sha ? [`**SHA:** ${params.head_sha}`] : []),
        ...(params.logs_url ? [`**Logs:** ${params.logs_url}`] : []),
        "",
        `**Root cause:** ${investigation.fix_description ?? "?"}`,
        "",
        `**Cost:** $${investigation.cost_usd.toFixed(4)}`,
        "",
        ...(investigation.diff ? [`\`\`\`diff\n${investigation.diff}\n\`\`\``] : []),
        "",
        "_Generated by Aegis CI auto-fix_",
      ].filter(Boolean).join("\n")

      const nearBudget = budget > 0 && investigation.cost_usd >= budget * 0.8
      const pr = nearBudget
        ? await createDraftPr({
            repo: params.repo,
            branch: investigation.fix_branch,
            title: `[ci-fix] ${investigation.fix_description ?? "Auto-fix"} (#${params.run_id})`,
            body: prBody + "\n\n> ⚠️ Budget nearly exhausted — opened as draft",
          })
        : await createPr({
            repo: params.repo,
            branch: investigation.fix_branch,
            title: `[ci-fix] ${investigation.fix_description ?? "Auto-fix"} (#${params.run_id})`,
            body: prBody,
          })

      if (!pr.success) {
        status.status = "failed"
        status.error = "PR creation failed"
        status.completed_at = Date.now()
        return
      }

      status.status = "pr_created"
      status.pr_url = pr.url
      status.pr_number = pr.number

      await notify({
        channels: repoConfig.notify,
        repo: params.repo,
        runId: params.run_id,
        status: "pr_created",
        prUrl: pr.url,
        costUsd: investigation.cost_usd,
      })

      // 3. Auto-merge if configured
      if (repoConfig.auto_merge && investigation.fix_branch && pr.number > 0) {
        const merged = await autoMerge({
          repo: params.repo,
          prNumber: pr.number,
          branch: investigation.fix_branch,
          allowedPaths: repoConfig.allowed_paths,
          requireHumanApproval: repoConfig.require_human_approval_comment,
        })

        if (merged) {
          status.status = "merged"
          await notify({
            channels: repoConfig.notify,
            repo: params.repo,
            runId: params.run_id,
            status: "merged",
            prUrl: pr.url,
          })
        }
      }

      status.completed_at = Date.now()
    } catch (err) {
      status.status = "failed"
      status.error = String(err)
      status.completed_at = Date.now()
    }
  })

  repoQueues.set(runKey, runPromise)

  // Return initial status immediately
  return {
    run_id: params.run_id,
    repo: params.repo,
    status: "queued",
    cost_usd: 0,
    started_at: Date.now(),
  }
}
